### ISSUE TITLE
Error when fit aggmap

### ISSUE THREAD

**Issue by tttender** [shenwanxiang/bidd-aggmap#17]
I used aggmap to transform my transcriptome data. The sample number of my data is 805 and the feature number is 17737. When I input my data to fit aggmap,  ValueError occurred: Buffer has the wrong number of dimensions (expected 1, got 2). I later found that this error occurs when the number of features is greater than or equal to 4096 and it works when the number is less than 4096.
![error1](https://user-images.githubusercontent.com/128064267/225669614-12b0d0f2-fe5b-4201-8780-4894ff25c9a2.png)
![error2](https://user-images.githubusercontent.com/128064267/225669678-55acf859-015f-4060-a7ad-682cd0918a5c.png)

**Comment by shenwanxiang** [comment]
Hi @tttender, you may try to downgrade the scipy version
 
pip install scipy==1.2.3
pip install umap-learn==0.3.9

or upgrade you umap-learn to 0.4.6 or above.

**Comment by tttender** [comment]
I tried downgrade the scipy version and  it did fix the problem. 
Thank you very much!
