### ISSUE TITLE
Error when using simply_explainer?

### ISSUE THREAD

**Issue by ivy-yuan** [shenwanxiang/bidd-aggmap#8]
I'm using aggmap to solve a binary classification problem. I followed the step and code exactly as what is showing, but I was faced up an error when using `simply_explainer` function. Here is what the error shows. Could anyone help me with this issue?

![图片](https://user-images.githubusercontent.com/39991878/154833677-364edc46-59c6-4f30-9de1-0f46adabd24f.png)

**Comment by shenwanxiang** [comment]
> I'm using aggmap to solve a binary classification problem. I followed the step and code exactly as what is showing, but I was faced up an error when using `simply_explainer` function. Here is what the error shows. Could anyone help me with this issue?
> 
> ![图片](https://user-images.githubusercontent.com/39991878/154833677-364edc46-59c6-4f30-9de1-0f46adabd24f.png)

Hi there! I think this is because your mp object is too old. You try using the new code to generate the mp object. Do remember 
to fit your mp object using the data

**Comment by shenwanxiang** [comment]
As you can see, the attribute "feature_names_reshape" only available when your mp object is fitted by the data: https://github.com/shenwanxiang/bidd-aggmap/blob/master/aggmap/map.py#L420
